site_name: Renesas Virtual MCU Rally

theme:
  name: material

nav:
  - Home: index.md
  - Installation:
    - WeBots simulator: webots_simulator.md
    - Simulation environment: simulation_environment.md
  - First steps:
    - Project setup: project_setup.md
    - Creating controllers: creating_controllers.md
  - Programming guide:
    - API functions: api_functions.md
    - Line following: line_following.md
    - State machine programming: state_machine_programming.md
  - Manuals:
    - Tuning the MCU car: tuning_the_mcucar.md
    - Building tracks: building_tracks.md
  - Competition:
    - Regulations: regulations.md
    - Guide for participants: guide_for_participants.md

plugins:
  - search 
  - with-pdf:
      author: Renesas Europe
      cover_title: Renesas Virtual MCU Rally
      cover_subtitle: Documentation and rules (draft aug. 2021)
      copyright: Subject to updates
      render_js: true
      headless_chrome_path: chromium-browser
      two_columns_level: 3
      ordered_chapter_level: 0
      output_path: ../../instructions.pdf
      show_anchors: true
